"""
Custom exceptions generated by app
"""


class UnsupportedSchema(Exception):
    """Incorrect message what can't be parsed"""
    def __str__(self):
        return "The query text does not match the expected schema."


class DataError(Exception):
    """Correct message scheme with incorrect data inside"""
    def __str__(self):
        return "Incorrect data in the query."


class DataBaseError(Exception):
    """All database errors grouped here"""
    def __str__(self):
        return "Something wrong with processing your query by database"
